version: 0.0
os: linux

#!/bin/bash
sudo su
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
chkconfig httpd on
cd /var/www/html
echo "<html><h1>This is server - 01 </h1></html>" > index.html
