# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pool:
- task: ECRPushImage@1
  inputs:
    regionName: 'us-west-1'
    imageSource: 'imagename'
    AWS_ACCESS_KEY_ID: 'AKIAT4N62DZH32UNWMML'
    AWS_SECRET_ACCESS_KEY: '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'
    sourceImageName: 'apteste'
    repositoryName: 'https://github.com/anderdedon/1sti'
    autoCreateRepository: true


#  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
