# Starter pipeline
- task: BeanstalkDeployApplication@1
  inputs:
    awsCredentials: 'eks'
    regionName: 'us-west-1'
    applicationName: '1sti'
    environmentName: '1sti'
    applicationType: 'version'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


- task: ECRPushImage@1
  inputs:
    regionName: 'us-west-1'
    imageSource: 'imagename'
    sourceImageName: 'teste'
    repositoryName: 'anderdedon.1sti'
    autoCreateRepository: true
    forceDockerNamingConventions: true